# Generated by Django 3.2.7 on 2021-10-23 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='feed_belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rssfeeds.rssfeed'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
