# Generated by Django 3.2.7 on 2021-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeeds', '0002_auto_20211023_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='feed_image',
            field=models.ImageField(blank=True, default='rssfeed.png', null=True, upload_to='rssfeeds'),
        ),
    ]
