# Generated by Django 3.2.7 on 2021-11-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_profile_image'),
        ('rssfeeds', '0003_rssfeed_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.subscriber'),
        ),
    ]
