# Generated by Django 3.2.7 on 2021-10-23 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestKeyword',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('personal_interests', models.ManyToManyField(blank=True, null=True, to='subscribers.InterestKeyword')),
            ],
        ),
    ]
