# Generated by Django 3.2.7 on 2021-11-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20211030_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='subscribers/'),
        ),
    ]
